# DeltaRedis Configuration File

# Login and connection information for the Redis server
RedisServer:
  URL: localhost
  Port: 6379
  HasPassword: False
  Password: DeltaRedis_Is_Great!

# Name of this server instance
ServerName: Bungeecord

# Used for debugging DeltaRedis
DebugMode: True
