# DeltaRedis Configuration File

# Login and connection information for the Redis server
RedisServer:
  URL: localhost
  Port: 6379
  HasPassword: False
  Password: DeltaRedis_Is_Great!

# Server name
ServerName: Lobby

# server type
ServerType: lobby

# Time in ticks for every online server and online player update
OnlineUpdatePeriod: 300

# Used for debugging DeltaRedis
DebugMode: True
